_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 80
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 80
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
alpha:
    value: 0.85
aux_loss:
    value: false
batch_size:
    value: 2
crop_size:
    value: 256
depth:
    value: 2
enc_final_channels:
    value: 512
fold:
    value: 1
gamma:
    value: 0.5
initial_lr:
    value: 0.0005
label_smoothing:
    value: 0.01
loss_name:
    value: mix
model_script_name:
    value: multitask_depth=2_fold_1_mix_32442_numsclass_6
model_type:
    value: multitask
n_epoch:
    value: 100
num_classes:
    value: 6
optimizer_type:
    value: adam
reduction:
    value: ""
scheduler_type:
    value: ReduceLR
threshold_lr:
    value: 1e-06
weight_decay:
    value: 1e-06
